name: Continuous Integration and Deployment
on:
  push:
    branches:
      - sign-and-verify-with-github-actions
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO try with node 12 too
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: make install
